export const environment = {
  production: false,
  tokenKey: 'token',
  host: 'https://localhost:4200/',
  baseUrl: '/',
  apiBaseUrl: '/api/',
  requestResetPasswordEndpoint: 'Users/auth/request-password-reset',
  passworResetEndpoint: 'Users/auth/reset-password',
  requestAccountUnlockEndpoint: 'Users/auth/request-account-unlock',
  unlockAccountEndpoint: 'Users/auth/unlock-account',
  productListViewEndpoint: 'Products/views/product-list',
  categoryEndpoint: 'Categories/',
  attributesEndpoint: 'Attributes/',
  productsEndpoint: 'Products/',
  discountsEndpoint: 'Discounts/',
  usersEndpoint: 'Users/',
  brandsEndpoint: 'Brands/',
  variantsEndpoint: 'ProductVariants/',
  purchasesEndpoint: 'Purchases/',
  providersEndpoint: 'Providers/',
  ordersEndpoint: 'Orders/',
  productImageEndpoint: 'ProductImages/',
};
